# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
from snakemake.io import glob_wildcards, expand
import sys
import os
import logging
import csv
import pandas as pd
import numpy as np

include: "rules/slurm.smk"
#configfile: "config/config.yaml"
  
#samples = pd.read_table("config/samples.tsv").set_index("sample", drop=False)  

sample_table = (
    pd.read_csv(
	"config/samples.tsv",
        sep="\t",
        dtype={"sample_name": str, "status": str},
        comment="#",
    )
    .set_index("sample_name", drop=False)
    .sort_index()
)


#retrieve bam path
def bam_from_sample(wildcards):
	return sample_table.loc[wildcards.sample_name, "bam"]

rule idxstat:
	input:
		bam_from_sample	
	output:
		"results/{sample_name}.stat"
	shell:
		"samtools idxstats {input} > {output}"
